# Generated by Django 3.2.8 on 2021-10-26 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='sobre',
            new_name='about',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, upload_to='photo'),
        ),
    ]
