# Generated by Django 3.2.8 on 2021-10-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cv',
            field=models.URLField(blank=True),
        ),
    ]
