# Generated by Django 3.2.8 on 2022-01-20 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
