# Generated by Django 3.2.8 on 2023-01-14 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20221227_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(blank=True, upload_to='photo'),
        ),
    ]
