# Generated by Django 3.2.8 on 2021-10-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_portfolio_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='tags',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='text',
            field=models.CharField(max_length=350),
        ),
    ]
