# Generated by Django 3.2.8 on 2021-10-28 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_eec'),
    ]

    operations = [
        migrations.AddField(
            model_name='eec',
            name='categoria',
            field=models.CharField(choices=[('educação', 'Educação'), ('experiência', 'Experiência'), ('Cursos', 'Cursos')], default='educação', max_length=12),
        ),
    ]
