# Generated by Django 3.2.8 on 2021-10-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_eec_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eec',
            name='categoria',
        ),
        migrations.AddField(
            model_name='eec',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('experience', 'Experience'), ('course', 'Course')], default='education', max_length=12),
        ),
    ]
