# Generated by Django 3.2.8 on 2021-10-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0012_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledge',
            old_name='icon',
            new_name='logo',
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(max_length=20),
        ),
    ]
