# Generated by Django 3.2.8 on 2021-10-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_auto_20211029_0743'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='icon',
        ),
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.FileField(default=1, upload_to='logo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='logo',
            field=models.FileField(upload_to='logo'),
        ),
    ]
