# Generated by Django 3.2.8 on 2022-12-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_auto_20220119_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledge',
            name='logo',
            field=models.ImageField(upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, upload_to='project'),
        ),
        migrations.AlterField(
            model_name='service',
            name='logo',
            field=models.ImageField(upload_to='logo'),
        ),
    ]
