# Generated by Django 3.2.8 on 2023-04-18 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_auto_20230114_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eec',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
