# Generated by Django 3.2.8 on 2023-05-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_auto_20230418_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eec',
            name='text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='alt',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='knowledge',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='project',
            name='text',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='service',
            name='alt',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='service',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
