# Generated by Django 3.2.8 on 2022-12-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_pt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conhecimento',
            name='logo',
            field=models.ImageField(upload_to='logo'),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='project'),
        ),
        migrations.AlterField(
            model_name='servico',
            name='logo',
            field=models.ImageField(upload_to='logo'),
        ),
    ]
